import test from 'node:test';import assert from 'node:assert/strict';
import {Battle,HEROES,generateMap,normalizeSave,freshSave,purchase,exchange,position,grantStarter,purchaseQuote} from '../public/js/engine.js';
test('500 procedural maps have continuous non-overlapping routes and available building pads',()=>{for(let seed=1;seed<=500;seed++){const m=generateMap(seed,seed%40+1),seen=new Set();assert.ok(m.pads.length>30);for(let i=0;i<m.cells.length;i++){const p=m.cells[i],key=p.c+','+p.r;assert.ok(!seen.has(key));seen.add(key);assert.ok(p.c>=0&&p.c<9);if(i)assert.equal(Math.abs(p.c-m.cells[i-1].c)+Math.abs(p.r-m.cells[i-1].r),1);}for(const p of m.pads)assert.ok(!seen.has(p.c+','+p.r));}});
test('placement initializes cooldown, respects currency and blocks the road',()=>{const b=new Battle(freshSave(),1),p=b.map.pads[0];assert.ok(b.place('iron',p.c,p.r).tower);assert.equal(b.energy,260);assert.ok(Number.isFinite(b.towers[0].cool));assert.ok(b.place('iron',p.c,p.r).error);assert.ok(b.place('hulk',p.c,p.r).error);const road=b.map.cells[2];assert.ok(b.place('spider',road.c,road.r).error);});
test('economy unlocks playable heroes, caps upgrades and prevents overdraft',()=>{const s=normalizeSave({coins:1000,diamonds:0});assert.ok(exchange(s,3));assert.equal(s.coins,700);assert.ok(purchase(s,'hulk'));assert.ok(s.unlocked.hulk);assert.equal(s.diamonds,0);assert.ok(purchase(s,'iron'));assert.equal(s.upgrades.iron,2);assert.equal(s.coins,600);assert.equal(exchange(s,7),false);assert.equal(exchange(s,-1),false);s.upgrades.iron=10;assert.equal(purchase(s,'iron'),false);});
test('all nine heroes attack, charge and execute their own ultimate',()=>{for(const id of Object.keys(HEROES)){const s=normalizeSave({unlocked:Object.fromEntries(Object.keys(HEROES).map(k=>[k,true]))}),b=new Battle(s,100),pad=b.map.pads.find(p=>b.map.cells.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<70));b.energy=1000;const t=b.place(id,pad.c,pad.r).tower;b.active=true;const segment=b.map.cells.findIndex(q=>Math.hypot(pad.x-q.x,pad.y-q.y)<60);b.spawn('boss');const e=b.enemies[0];e.d=segment*40;e.hp=e.maxHp=100000;e.speed=0;Object.assign(e,position(b.map,e.d));for(let i=0;i<200;i++)b.update(.05);if(id==='spider'){assert.equal(e.hp,100000);assert.ok(e.web>0||b.shots.some(p=>p.hero==='spider'));}else assert.ok(e.hp<100000,id+' attacks');assert.ok(t.charge>0,id+' charges');t.charge=100;e.web=3;assert.ok(b.ultimate(t).ok,id+' ultimate');assert.equal(t.charge,0);}});
test('Spider only pulls webbed targets and Iron beam is limited to four blocks',()=>{const s=freshSave(),b=new Battle(s,4);b.energy=1000;const p=b.map.pads[0],t=b.place('spider',p.c,p.r).tower;t.charge=100;b.spawn('boss');const e=b.enemies[0];Object.assign(e,{x:t.x+30,y:t.y,d:200});assert.ok(b.ultimate(t).error);assert.equal(t.charge,100);e.web=3;assert.ok(b.ultimate(t).ok);assert.equal(e.d,80);const iron={...t,hero:'iron',damage:30,charge:100};b.towers.push(iron);b.enemies=[];for(const [x,y]of[[60,0],[150,0],[190,0],[80,50]]){b.spawn('boss');Object.assign(b.enemies.at(-1),{x:iron.x+x,y:iron.y+y,hp:500,maxHp:500,d:100-x});}assert.ok(b.ultimate(iron).ok);assert.deepEqual(b.enemies.map(e=>e.hp),[350,350,500,500]);});
test('finish rewards once, loss does not advance, and paused simulation has no clock dependency',()=>{const s=freshSave(),b=new Battle(s,1);b.finish(true);const coins=s.coins;assert.equal(s.stage,2);b.finish(true);assert.equal(s.coins,coins);const loss=new Battle(s,2);loss.kills=10;loss.finish(false);assert.equal(s.stage,2);assert.equal(s.coins,coins+20);const c=new Battle(s,3);c.startWave();c.update(.1);const timer=c.spawnTimer;assert.equal(c.spawnTimer,timer);});
test('new player can win complete stages with basic heroes on 12 different maps',()=>{for(let seed=1;seed<=12;seed++){const s=normalizeSave(null),b=new Battle(s,seed);function placeBest(id){const spots=b.map.pads.filter(p=>!b.towers.some(t=>t.c===p.c&&t.r===p.r));spots.sort((a,c)=>score(c)-score(a));function score(p){let val=0;for(const q of b.map.cells){const d=Math.hypot(p.x-q.x,p.y-q.y);if(d<HEROES[id].range)val+=1-d/HEROES[id].range*.25;}val-=b.towers.reduce((n,t)=>n+(Math.hypot(p.x-t.x,p.y-t.y)<85?1.3:0),0);return val;}if(spots[0])b.place(id,spots[0].c,spots[0].r);}
placeBest('iron');placeBest('iron');placeBest('spider');let steps=0;while(!b.ended&&steps++<20000){if(!b.active)b.startWave();if(b.energy>=160&&b.towers.length<12)placeBest(b.towers.length%4===3?'spider':'iron');for(const t of b.towers)if(t.charge>=100)b.ultimate(t);b.update(.1);b.events=[];}assert.ok(b.ended,'ends '+seed);assert.ok(b.reward.won,'wins seed '+seed+' with '+b.kills+' kills');}});

test('starter bonus is persistent and allows both basic upgrades plus a new hero',()=>{
 let s=normalizeSave(null);assert.equal(grantStarter(s),true);assert.equal(s.coins,500);assert.ok(purchase(s,'spider'));assert.ok(purchase(s,'iron'));assert.ok(purchase(s,'hulk'));assert.equal(s.coins,0);assert.equal(s.diamonds,0);assert.equal(s.upgrades.spider,2);assert.equal(s.upgrades.iron,2);assert.ok(s.unlocked.hulk);s=normalizeSave(JSON.parse(JSON.stringify(s)));assert.equal(grantStarter(s),false);assert.equal(s.coins,0);assert.ok(s.unlocked.hulk);assert.equal(s.upgrades.spider,2);
});
test('mixed diamond and gold purchase charges exactly the shown quote and is atomic',()=>{
 const s=normalizeSave({coins:200,diamonds:2});const q=purchaseQuote(s,'thor');assert.equal(q.gold,200);assert.equal(q.diamonds,2);assert.equal(q.convert,2);assert.ok(q.affordable);assert.ok(purchase(s,'thor'));assert.equal(s.coins,0);assert.equal(s.diamonds,0);assert.ok(s.unlocked.thor);const before=JSON.stringify(s);assert.equal(purchase(s,'strange'),false);assert.equal(JSON.stringify(s),before);
});
test('Spider never damages or refreshes webbed enemies and two spiders reserve separate targets',()=>{
 const b=new Battle(normalizeSave(null),7);b.energy=1000;const p=b.map.pads.find(p=>b.map.cells.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<60));const t=b.place('spider',p.c,p.r).tower;const p2=b.map.pads.find(q=>q!==p&&Math.hypot(q.x-p.x,q.y-p.y)<70);const t2=b.place('spider',p2.c,p2.r).tower;
 const d=b.map.cells.findIndex(q=>Math.hypot(p.x-q.x,p.y-q.y)<60)*40;b.active=true;
 for(let i=0;i<3;i++){b.spawn('boss');Object.assign(b.enemies.at(-1),{d:d+i*5,speed:0,hp:1000,maxHp:1000,...position(b.map,d+i*5)});}
 b.enemies[2].web=5;for(const t of b.towers)t.cool=0;b.update(.001);const shots=b.shots.filter(p=>p.hero==='spider');assert.equal(shots.length,2);assert.notEqual(shots[0].target,shots[1].target);assert.ok(shots.every(p=>p.target!==b.enemies[2]));
 for(let i=0;i<20;i++)b.update(.05);assert.ok(b.enemies.every(e=>e.hp===1000));assert.ok(b.enemies.every(e=>e.web>0));assert.equal(b.shots.length,0);
 const e=b.enemies[0],remaining=e.web;b.impact({target:e,tower:t,hero:'spider',damage:999});assert.equal(e.web,remaining);assert.equal(e.hp,1000);
 e.web=0;e.slow=3;t.cool=0;t2.cool=10;b.update(.001);assert.ok(b.shots.some(p=>p.target===e));
});
test('Spider upgrade improves control without damage and updates deployed heroes',()=>{
 const s=normalizeSave({coins:500}),b=new Battle(s,1);const p=b.map.pads[0],t=b.place('spider',p.c,p.r).tower;const old={range:t.range,duration:t.webDuration,factor:t.webFactor,rate:t.rate};assert.ok(purchase(s,'spider'));b.applyUpgrade('spider');assert.equal(t.damage,0);assert.ok(t.range>old.range);assert.ok(t.webDuration>old.duration);assert.ok(t.webFactor<old.factor);assert.ok(t.rate<old.rate);
});
